# Generated by Django 4.1.7 on 2023-03-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('company_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=10)),
                ('invoice_currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiced_amount', models.IntegerField()),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=9, unique=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.PROTECT, related_name='user_invoice', to='leads.user')),
            ],
        ),
    ]
